server:
  port: 8091

spring:
  application:
    name: dubbo-samples-consumer-springCloud

dubbo:
  application:
    name: ${spring.application.name}
    qosPort: 33333
  registry:
    address: zookeeper://node0:2181
    timeout: 5000
  protocol:
    name: dubbo
    port: 20891
  # 扫描 @DubboService 注解
  scan:
    base-packages: org.example.controller
