spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: 123456
  application:
    name: dubbo-samples-provider-springCloud

server:
  port: 8091

dubbo:
  application:
    name: ${spring.application.name}
    qosPort: 22222
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 5000
  protocol:
    name: dubbo
    port: 20891
  # 扫描 @DubboService 注解
  scan:
    base-packages: org.example.service
