spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://node0:3306/greatecommunity?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  application:
    name: dubbo-samples-provider-springCloud
  redis:
    database: 11
    host: node0
    port: 6379
  main:
    allow-bean-definition-overriding: true
server:
  port: 8091

dubbo:
  application:
    name: ${spring.application.name}
    qosPort: 22222
  registry:
    address: zookeeper://node0:2181
    timeout: 5000
  protocol:
    name: dubbo
    port: 20891
  # 扫描 @DubboService 注解
  scan:
    base-packages: org.example.service
# slf4j日志配置
logging:
  level:
    root: info